spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/project?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: project
    password: 1234
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
  data:
    redis:
      host: host.docker.internal
      port: 6379