spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: dkwktm45
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: localhost
      port: 6379